/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasipenyewaanstudiomgrproud;
import java.sql.*;
import javax.swing.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.awt.*;
import java.awt.Container;
import aplikasipenyewaanstudiomgrproud.koneksi;
import java.io.File;
/**
 *
 * @author aryos
 */
public class PaketanStudio extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    int durasisewa, hargapkt, jmlharga;
    /**
     * Creates new form PaketanStudio
     */
    public PaketanStudio() {
        initComponents();
        datatablepaketanstudio();
        setLocationRelativeTo(this);
        
    }

    protected void aktif() {
        txtkdpaketan.setEnabled(true);
        txtnobook.setEnabled(true);
        txtidop.setEnabled(true);
        txtidpel.setEnabled(true);
        txtnamapel.setEnabled(true);
        txttglsewa.setEnabled(true);
        txtdurasi.setEnabled(true);
        txthargapkt.setEnabled(true);
        txttlbiaya.setEnabled(true);
        txtbyrdp.setEnabled(true);
        txtsisabyr.setEnabled(true);
        txtkdpaketan.requestFocus();
    }
    
    protected void kosong() {
        txtkdpaketan.setText("");
        txtnobook.setText("");
        txtidop.setText("");
        txtidpel.setText("");
        txtnamapel.setText("");
        txttglsewa.setText("");
        txtdurasi.setText("");
        txthargapkt.setText("");
        txttlbiaya.setText("");
        txtbyrdp.setText("");
        txtsisabyr.setText("");
        txtcari.setText("");
        cbstudio.setSelectedIndex(0);
        cbjammsk.setSelectedIndex(0);
        cbjamsls.setSelectedIndex(0);
        rdbronze.setSelected(true);
        rdsilver.setSelected(true);
        rdgold.setSelected(true);
        
    }
    
    protected void datatablepaketanstudio() {
        Object[] Baris = {"Kode Paketan","No Book","Id Operator","Id Pelanggan", "Nama Pelanggan", "Tanggal Sewa", "Studio", "Jam Masuk", "Jam Selesai", "Durasi", "Menu Paket","Harga Paket", "Total Biaya", "Bayar Dp","Sisa Bayar"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelpaketanstudio.setModel(tabmode);
        String sql = "select * from paketanstudio";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("kd_paketan");
                String b = hasil.getString("nmrbooking");
                String c = hasil.getString("id_operator");
                String d = hasil.getString("id_pelanggan");
                String e = hasil.getString("nama_pelanggan");
                String f = hasil.getString("tglsewa");
                String g = hasil.getString("studio");
                String h = hasil.getString("jammsk");
                String i = hasil.getString("jamsls");
                String j = hasil.getString("durasi");
                String k = hasil.getString("menu_pkt");
                String l = hasil.getString("harga_pkt");
                String m = hasil.getString("ttlbiaya");
                String n = hasil.getString("dp");
                String o = hasil.getString("sisabayar");
                
                String[] data = {a, b, c, d, e, f, g, h, i, j, k, l, m, n, o};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrouppkt = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtkdpaketan = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidpel = new javax.swing.JTextField();
        txtnamapel = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnobook = new javax.swing.JTextField();
        btncarinobook = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtidop = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtdurasi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txthargapkt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtbyrdp = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtsisabyr = new javax.swing.JTextField();
        btnbayar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txttlbiaya = new javax.swing.JTextField();
        rdbronze = new javax.swing.JRadioButton();
        rdsilver = new javax.swing.JRadioButton();
        rdgold = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbjammsk = new javax.swing.JComboBox<>();
        cbjamsls = new javax.swing.JComboBox<>();
        cbstudio = new javax.swing.JComboBox<>();
        txttglsewa = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpaketanstudio = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        btncaripaketan = new javax.swing.JButton();
        btnbackop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 0, 255));

        jPanel10.setBackground(new java.awt.Color(255, 153, 255));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel18.setText("KODE PAKETAN");

        txtkdpaketan.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtkdpaketan, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtkdpaketan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PAKETAN STUDIO ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 0, 204));
        jPanel2.setForeground(new java.awt.Color(255, 153, 255));

        jLabel2.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel2.setText("ID PELANGGAN");

        jLabel3.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel3.setText("NAMA PELANGGAN");

        txtidpel.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N

        txtnamapel.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel1.setText("NO BOOKING");

        txtnobook.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N

        btncarinobook.setBackground(new java.awt.Color(255, 255, 255));
        btncarinobook.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        btncarinobook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cari.jpg"))); // NOI18N
        btncarinobook.setText("CARI");
        btncarinobook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncarinobookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnobook, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncarinobook)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnobook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncarinobook))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtnamapel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtidpel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtidpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnamapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 153, 255));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel16.setText("ID OPERATOR");

        txtidop.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtidop, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtidop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 0, 204));

        jLabel12.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel12.setText("DURASI SEWA");

        txtdurasi.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel13.setText("MENU PAKET");

        jLabel14.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel14.setText("HARGA PAKET");

        txthargapkt.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        txthargapkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargapktActionPerformed(evt);
            }
        });
        txthargapkt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthargapktKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel15.setText("BAYAR DP");

        txtbyrdp.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel17.setText("SISA BAYAR");

        txtsisabyr.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N

        btnbayar.setBackground(new java.awt.Color(255, 255, 255));
        btnbayar.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        btnbayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tunggakan.png"))); // NOI18N
        btnbayar.setText("BAYAR");
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel19.setText("TOTAL BIAYA");

        txttlbiaya.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N

        rdbronze.setText("BRONZE");
        rdbronze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbronzeActionPerformed(evt);
            }
        });

        rdsilver.setText("SILVER");
        rdsilver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdsilverActionPerformed(evt);
            }
        });

        rdgold.setText("GOLD");
        rdgold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdgoldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txthargapkt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addComponent(txtdurasi, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(rdbronze)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdsilver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdgold))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbyrdp)
                            .addComponent(txtsisabyr)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(25, 25, 25)
                        .addComponent(txttlbiaya)))
                .addGap(18, 18, 18)
                .addComponent(btnbayar)
                .addGap(1, 1, 1))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtdurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbronze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdsilver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdgold))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthargapkt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttlbiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbyrdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbayar))
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsisabyr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 0, 204));
        jPanel5.setForeground(new java.awt.Color(153, 255, 102));

        jLabel5.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel5.setText("TANGGAL SEWA");

        jLabel6.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel6.setText("STUDIO");

        jLabel9.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel9.setText("JAM MASUK");

        jLabel11.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel11.setText("JAM SELESAI");

        cbjammsk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00.00", "01.00", "02.00", "03.00", "04.00", "05.00", "06.00", "07.00", "08.00", "09.00", "10.00", "11.00", "12.00", "13.00", "14.00", "15.00", "16.00", "17.00", "18.00", "19.00", "20.00", "21.00", "22.00", "23.00" }));

        cbjamsls.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00.00", "01.00", "02.00", "03.00", "04.00", "05.00", "06.00", "07.00", "08.00", "09.00", "10.00", "11.00", "12.00", "13.00", "14.00", "15.00", "16.00", "17.00", "18.00", "19.00", "20.00", "21.00", "22.00", "23.00" }));

        cbstudio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STUDIO 1", "STUDIO 2", "STUDIO 3", "STUDIO MUSIK" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbjammsk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbjamsls, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbstudio, 0, 167, Short.MAX_VALUE)
                    .addComponent(txttglsewa))
                .addGap(22, 22, 22))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttglsewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbjammsk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbjamsls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnsave.setBackground(new java.awt.Color(255, 255, 255));
        btnsave.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save.png"))); // NOI18N
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(255, 255, 255));
        btnedit.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit.jpg"))); // NOI18N
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(255, 255, 255));
        btndelete.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.png"))); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(255, 255, 255));
        btnclear.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/clear.png"))); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        tabelpaketanstudio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Paketan", "No.Booking", "Id Operator", "Id Pelanggan", "Nama Pelanggan", "Tanggal Sewa", "Studio", "Jam Masuk", "Jam Selesai", "Durasi", "Menu Paket", "Harga Paket", "Total Biaya", "Bayar DP", "Sisa Bayar"
            }
        ));
        tabelpaketanstudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpaketanstudioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelpaketanstudio);

        jPanel6.setBackground(new java.awt.Color(255, 153, 255));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        jLabel10.setText("CARI PAKETAN");

        txtcari.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N

        btncaripaketan.setBackground(new java.awt.Color(255, 255, 255));
        btncaripaketan.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        btncaripaketan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cari.jpg"))); // NOI18N
        btncaripaketan.setText("CARI");
        btncaripaketan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaripaketanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(11, 11, 11)
                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncaripaketan)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncaripaketan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnbackop.setBackground(new java.awt.Color(255, 255, 255));
        btnbackop.setFont(new java.awt.Font("Perpetua", 1, 16)); // NOI18N
        btnbackop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back.png"))); // NOI18N
        btnbackop.setText("BACK");
        btnbackop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnedit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnclear)))
                .addGap(29, 29, 29))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnbackop))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsave)
                            .addComponent(btnedit)
                            .addComponent(btndelete)
                            .addComponent(btnclear))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbackop, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncarinobookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncarinobookActionPerformed
        // TODO add your handling code here:
        String sql = "select * from bookingstudio where nmrbooking = '" + txtnobook.getText() + "'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("nmrbooking");
                String b = hasil.getString("id_operator");
                String c = hasil.getString("id_pelanggan");
                String d = hasil.getString("nama_pelanggan");
                String e = hasil.getString("tglsewa");
                String f = hasil.getString("studio");
                String g = hasil.getString("jammsk");
                String h = hasil.getString("jamsls");
                String i = hasil.getString("durasi");
                String j = hasil.getString("ttlbiaya");
                String k = hasil.getString("dp");

                txtnobook.setText(a);
                txtidop.setText(b);
                txtidpel.setText(c);
                txtnamapel.setText(d);
                txttglsewa.setText(e);
                cbstudio.setSelectedItem(f);
                cbjammsk.setSelectedItem(g);
                cbjamsls.setSelectedItem(h);
                txtdurasi.setText(i);
                txttlbiaya.setText(j);
                txtbyrdp.setText(k);

                txtnobook.setEnabled(true);
                txtidop.setEnabled(true);
                txtidpel.setEnabled(true);
                txtnamapel.setEnabled(true);
                txttglsewa.setEnabled(true);
                cbstudio.setEnabled(true);
                cbjammsk.setEnabled(true);
                cbjamsls.setEnabled(true);
                txtdurasi.setEnabled(true);
                txttlbiaya.setEnabled(true);
                txtbyrdp.setEnabled(true);

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btncarinobookActionPerformed

    private void txthargapktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargapktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargapktActionPerformed

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
        // TODO add your handling code here:
        int totalbiaya, bayardp, total, durasisewa, hargapkt, jmlharga;
        
        durasisewa = Integer.parseInt(txtdurasi.getText());
        hargapkt = Integer.parseInt(txthargapkt.getText());
        
        jmlharga=(durasisewa*hargapkt);
        
        txttlbiaya.setText(Integer.toString(jmlharga));
        
        //input nilai
        totalbiaya = Integer.parseInt(txttlbiaya.getText());
        bayardp = Integer.parseInt(txtbyrdp.getText());

        //rumus
        total = totalbiaya - bayardp;

        //output
        txtsisabyr.setText(Integer.toString(total));
    }//GEN-LAST:event_btnbayarActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String sql = "insert into paketanstudio values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtkdpaketan.getText());
            stat.setString(2, txtnobook.getText());
            stat.setString(3, txtidop.getText());
            stat.setString(4, txtidpel.getText());
            stat.setString(5, txtnamapel.getText());
            stat.setString(6, txttglsewa.getText());
            stat.setString(7, cbstudio.getSelectedItem().toString());
            stat.setString(8, cbjammsk.getSelectedItem().toString());
            stat.setString(9, cbjamsls.getSelectedItem().toString());
            stat.setString(10, txtdurasi.getText());
            String pkt = "";
            if (rdbronze.isSelected() == true) {
                pkt = "Bronze";
            } else if (rdsilver.isSelected() == true) {
                pkt = "Silver";
            } else if (rdgold.isSelected() == true) {
                pkt = "Gold";
            }
            stat.setString(11, pkt);
            stat.setString(12, txthargapkt.getText());
            stat.setString(13, txttlbiaya.getText());
            stat.setString(14, txtbyrdp.getText());
            stat.setString(15, txtsisabyr.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            txtkdpaketan.requestFocus();
            datatablepaketanstudio();
            rdbronze.setSelected(false);
            rdsilver.setSelected(false);
            rdgold.setSelected(false);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
        }
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "update paketanstudio set nmrbooking=?,id_operator=?,id_pelanggan=?,nama_pelanggan=?,tglsewa=?,studio=?,jammsk=?,jamsls=?,durasi=?,menu_pkt=?,harga_pkt=?,ttlbiaya=?,dp=?,sisabayar=? where kd_paketan=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtnobook.getText());
            stat.setString(2, txtidop.getText());
            stat.setString(3, txtidpel.getText());
            stat.setString(4, txtnamapel.getText());
            stat.setString(5, txttglsewa.getText());
            stat.setString(6, cbstudio.getSelectedItem().toString());
            stat.setString(7, cbjammsk.getSelectedItem().toString());
            stat.setString(8, cbjamsls.getSelectedItem().toString());
            stat.setString(9, txtdurasi.getText());
            String pkt = "";
            if (rdbronze.isSelected() == true) {
                pkt = "Bronze";
            } else if (rdsilver.isSelected() == true) {
                pkt = "Silver";
            } else if (rdgold.isSelected() == true) {
                pkt = "Gold";
            }
            stat.setString(10, pkt);
            stat.setString(11,txthargapkt.getText());
            stat.setString(12,txttlbiaya.getText());
            stat.setString(13,txtbyrdp.getText());
            stat.setString(14,txtsisabyr.getText());
            stat.setString(15,txtkdpaketan.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            txtnobook.requestFocus();
            datatablepaketanstudio();
            rdbronze.setSelected(false);
            rdsilver.setSelected(false);
            rdgold.setSelected(false);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok == 0) {
            String sql = "Delete From paketanstudio where kd_paketan='" + txtkdpaketan.getText() + "'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil Dihapus");
                kosong();
                txtkdpaketan.requestFocus();
                datatablepaketanstudio();
                rdbronze.setSelected(false);
                rdsilver.setSelected(false);
                rdgold.setSelected(false);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" + e);
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        kosong();
        datatablepaketanstudio();
        rdbronze.setSelected(false);
        rdsilver.setSelected(false);
        rdgold.setSelected(false);
    }//GEN-LAST:event_btnclearActionPerformed

    private void btncaripaketanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaripaketanActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"Kode Paketan","No Book","Id Operator","Id Pelanggan", "Nama Pelanggan", "Tanggal Sewa", "Studio", "Jam Masuk", "Jam Selesai", "Durasi", "Menu Paket","Harga Paket", "Total Biaya", "Bayar Dp","Sisa Bayar"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelpaketanstudio.setModel(tabmode);
        String sql = "select * from paketanstudio where nama_pelanggan like '%"+txtcari.getText()+"%'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("kd_paketan");
                String b = hasil.getString("nmrbooking");
                String c = hasil.getString("id_operator");
                String d = hasil.getString("id_pelanggan");
                String e = hasil.getString("nama_pelanggan");
                String f = hasil.getString("tglsewa");
                String g = hasil.getString("studio");
                String h = hasil.getString("jammsk");
                String i = hasil.getString("jamsls");
                String j = hasil.getString("durasi");
                String k = hasil.getString("menu_pkt");
                String l = hasil.getString("harga_pkt");
                String m = hasil.getString("ttlbiaya");
                String n = hasil.getString("dp");
                String o = hasil.getString("sisabayar");
                
                String[] data = {a, b, c, d, e, f, g, h, i, j, k, l, m, n, o};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btncaripaketanActionPerformed

    private void rdbronzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbronzeActionPerformed
        // TODO add your handling code here:
        txthargapkt.setText("200000");
    }//GEN-LAST:event_rdbronzeActionPerformed

    private void rdsilverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdsilverActionPerformed
        // TODO add your handling code here:
        txthargapkt.setText("250000");
    }//GEN-LAST:event_rdsilverActionPerformed

    private void rdgoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdgoldActionPerformed
        // TODO add your handling code here:
        txthargapkt.setText("300000");
    }//GEN-LAST:event_rdgoldActionPerformed

    private void tabelpaketanstudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpaketanstudioMouseClicked
        // TODO add your handling code here:
        int bar = tabelpaketanstudio.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        String j = tabmode.getValueAt(bar, 9).toString();
        String k = tabmode.getValueAt(bar, 10).toString();
        String l = tabmode.getValueAt(bar, 11).toString();
        String m = tabmode.getValueAt(bar, 12).toString();
        String n = tabmode.getValueAt(bar, 13).toString();
        String o = tabmode.getValueAt(bar, 14).toString();

        txtkdpaketan.setText(a);
        txtnobook.setText(b);
        txtidop.setText(c);
        txtidpel.setText(d);
        txtnamapel.setText(e);
        txttglsewa.setText(f);
        cbstudio.setSelectedItem(g);
        cbjammsk.setSelectedItem(h);
        cbjamsls.setSelectedItem(i);
        txtdurasi.setText(j);
        
        if (k.equals("Bronze")) {
            rdbronze.setSelected(true);
            rdsilver.setSelected(false);
            rdgold.setSelected(false);
        }
        if (k.equals("Silver")) {
            rdsilver.setSelected(true);
            rdgold.setSelected(false);
            rdbronze.setSelected(false);
        }
        if (k.equals("Gold")) {
            rdgold.setSelected(true);
            rdbronze.setSelected(false);
            rdsilver.setSelected(false);
        }
        txthargapkt.setText(l);
        txttlbiaya.setText(m);
        txtbyrdp.setText(n);
        txtsisabyr.setText(o); 
    }//GEN-LAST:event_tabelpaketanstudioMouseClicked

    private void txthargapktKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargapktKeyReleased
        // TODO add your handling code here:
        int durasisewa, hargapkt, jmlharga;
        
        durasisewa = Integer.parseInt(txtdurasi.getText());
        hargapkt = Integer.parseInt(txthargapkt.getText());
        
        jmlharga=(durasisewa*hargapkt);
        
        txttlbiaya.setText(Integer.toString(jmlharga));
        
    }//GEN-LAST:event_txthargapktKeyReleased

    private void btnbackopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackopActionPerformed
        // TODO add your handling code here:
        new menuutama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaketanStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaketanStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaketanStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaketanStudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaketanStudio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbackop;
    private javax.swing.JButton btnbayar;
    private javax.swing.JButton btncarinobook;
    private javax.swing.JButton btncaripaketan;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnsave;
    private javax.swing.ButtonGroup buttonGrouppkt;
    private javax.swing.JComboBox<String> cbjammsk;
    private javax.swing.JComboBox<String> cbjamsls;
    private javax.swing.JComboBox<String> cbstudio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbronze;
    private javax.swing.JRadioButton rdgold;
    private javax.swing.JRadioButton rdsilver;
    private javax.swing.JTable tabelpaketanstudio;
    private javax.swing.JTextField txtbyrdp;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtdurasi;
    private javax.swing.JTextField txthargapkt;
    private javax.swing.JTextField txtidop;
    private javax.swing.JTextField txtidpel;
    private javax.swing.JTextField txtkdpaketan;
    private javax.swing.JTextField txtnamapel;
    private javax.swing.JTextField txtnobook;
    private javax.swing.JTextField txtsisabyr;
    private javax.swing.JTextField txttglsewa;
    private javax.swing.JTextField txttlbiaya;
    // End of variables declaration//GEN-END:variables
}
